/*
 * MDI_private_interface.h
 *
 *  Created on: Feb 15, 2025
 *      Author: molnar
 */

#ifndef MDI_MODULEDATAINTERCONNECT_INTERFACE_MDI_PRIVATE_INTERFACE_H_
#define MDI_MODULEDATAINTERCONNECT_INTERFACE_MDI_PRIVATE_INTERFACE_H_
#include "app_types.h"
#include "MDI_public_interface.h"

typedef union
{
    MDI_INTERCONNECT_STRUCT_FACTORY_d(boolean);
    MDI_INTERCONNECT_STRUCT_FACTORY_d(uint8_t);
    MDI_INTERCONNECT_STRUCT_FACTORY_d(uint16_t);
    MDI_INTERCONNECT_STRUCT_FACTORY_d(uint32_t);
    MDI_INTERCONNECT_STRUCT_FACTORY_d(int8_t);
    MDI_INTERCONNECT_STRUCT_FACTORY_d(int16_t);
    MDI_INTERCONNECT_STRUCT_FACTORY_d(int32_t);
    MDI_INTERCONNECT_STRUCT_FACTORY_d(float);
} MDI_Interconnect_u;

#endif /* MDI_MODULEDATAINTERCONNECT_INTERFACE_MDI_PRIVATE_INTERFACE_H_ */
